# Generated by Django 5.2 on 2026-03-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juggle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='interval_duration_minutes',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='interval_duration_seconds',
            field=models.IntegerField(default=5),
        ),
    ]
