# Generated by Django 5.2 on 2026-03-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juggle', '0002_remove_globalsettings_interval_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalsettings',
            old_name='interval_duration_seconds',
            new_name='interval_duration_minutes',
        ),
    ]
