# Generated by Django 5.2 on 2026-03-18 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juggle', '0003_rename_interval_duration_seconds_globalsettings_interval_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='jugglesession',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to='juggle.product'),
        ),
    ]
