# Generated by Django 5.2 on 2026-03-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juggle', '0004_product_stock_alter_jugglesession_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reserved_cb',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
