# Generated by Django 5.2 on 2026-03-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juggle', '0005_user_reserved_cb'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Generic', max_length=255),
        ),
    ]
