# Generated by Django 5.2 on 2026-03-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juggle', '0007_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_juggling',
            field=models.BooleanField(default=True),
        ),
    ]
