# Generated by Django 5.2 on 2026-03-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juggle', '0009_product_delivery_fee_product_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_juggler',
            field=models.BooleanField(default=False),
        ),
    ]
