# Generated by Django 5.2 on 2026-03-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juggle', '0011_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='site_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='total_site_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
