# Generated by Django 5.2 on 2026-03-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juggle', '0013_product_attributes_category_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_limited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_seller_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
