# Generated by Django 5.2 on 2026-03-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juggle', '0014_product_is_limited_user_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_license',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
