# Generated by Django 5.2 on 2026-03-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juggle', '0015_user_business_license_user_seller_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=20),
        ),
    ]
