# Generated by Django 5.2 on 2026-03-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juggle', '0016_user_seller_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_proof',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/address/'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_details_proof',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/bank/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/id/'),
        ),
        migrations.AddField(
            model_name='user',
            name='import_license',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/import/'),
        ),
        migrations.AddField(
            model_name='user',
            name='tin_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vat_registration',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/vat/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_license',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/business/'),
        ),
    ]
