# Generated by Django 5.2 on 2026-03-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juggle', '0017_user_address_proof_user_bank_details_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deals_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pyramid_tier',
            field=models.IntegerField(default=100),
        ),
    ]
