# Generated by Django 5.2 on 2026-09-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juggle', '0019_user_pending_balance_pyramid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
