# Generated by Django 5.2 on 2026-09-13 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juggle', '0020_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SALE', 'Product Sold'), ('JUGGLE_CLAIMED', 'Juggle Claimed'), ('JUGGLE_EXPIRED', 'Juggle Expired'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_SENT', 'Payment Sent'), ('PYRAMID_COMPLETE', 'Pyramid Complete'), ('CB_CREDITED', 'CB Credited'), ('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit'), ('SYSTEM', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
